<?php
/**
 * @CreateTime:   2021/1/3 1:21 上午
 * @Author:       huizhang  <2788828128@qq.com>
 * @Copyright:    copyright(2020) Easyswoole all rights reserved
 * @Description:  延迟队列进程处理
 */

namespace Huizhang\DelayQueue;

use EasySwoole\Component\Process\Socket\AbstractUnixProcess;
use EasySwoole\Component\Process\Socket\UnixProcessConfig;
use Swoole\Coroutine;
use Swoole\Coroutine\Socket;

class ConsumerProcess extends AbstractUnixProcess
{

    public function __construct(UnixProcessConfig $config)
    {
        ini_set('memory_limit', Config::getInstance()->getMem());
        parent::__construct($config);
    }

    public function run($arg)
    {
        /** @var $queue Queue */
        $queue = $arg;
        /** @var $consumer ConsumerAbstract */
        $namespace = "{$queue->getClass()}";
        $consumer = new $namespace;
        $consumer->queue = $queue;
        $consumer->init();
        for ($i = 0; $i < $queue->getCoroutineNum(); $i++) {
            Coroutine::create(function () use ($queue, $consumer) {
                while (true) {
                    try {
                        // TODO:: 先检查缓存文件中是否包含数据
                        $data = Core::getInstance()
                        ->pop(
                            $queue->getRedisAlias()
                            , $queue->getAlias()
                            , time() - $queue->getDelayTime()
                            , $queue->getLimit()
                        );
                        // TODO:: 从延迟队列取出的数据，要进行文件缓存
                        if (!empty($data)) {
                            $consumer->deal($data);
                        }
                    } catch (\Throwable $e) {
                        $consumer->onException($e, $data??[]);
                        break;
                    }
                    Coroutine::sleep(1);
                }
            });
        }
        return parent::run($arg); // TODO: Change the autogenerated stub
    }

    function onAccept(Socket $socket)
    {
        // TODO: Implement onAccept() method.
    }
}
